version: '3.3'

services:
  postgres:
    image: postgres:14
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin_root
      POSTGRES_PASSWORD: AdminPassword123
      POSTGRES_DB: shop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

#  shop-server:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: shop_server_container
#    ports:
#      - "8080:6000"
#    depends_on:
#      - postgres
#    environment:
#      DB_HOST: postgres
#      DB_PORT: 5432
#      DB_USER: admin_root
#      DB_PASSWORD: AdminPassword123
#      DB_NAME: shop_db
#    volumes:
#      - .:/app
#    command: >
#      sh -c "npm install -g @nestjs/cli &&
#             nest new shop-server --skip-git --package-manager npm --directory ./ &&
#             npm install &&
#             npm run build &&
#             npm run start:prod"

volumes:
  postgres_data:
